<?xml version="1.0" encoding="UTF-8"?>
<tileset name="tileset_underwater" tilewidth="32" tileheight="32" tilecount="112" columns="8">
 <image source="../image/tile/tileset_underwater.png" width="256" height="448"/>
 <tile id="0" type="floor"/>
 <tile id="1" type="floor"/>
 <tile id="2" type="floor"/>
 <tile id="3" type="floor"/>
 <tile id="4" type="floor"/>
 <tile id="5" type="wall"/>
 <tile id="6" type="exit"/>
 <tile id="7" type="wall"/>
 <tile id="8" type="floor"/>
 <tile id="9" type="floor"/>
 <tile id="10" type="floor"/>
 <tile id="11" type="floor"/>
 <tile id="12" type="none"/>
 <tile id="13" type="wall"/>
 <tile id="14" type="exit"/>
 <tile id="15" type="wall"/>
 <tile id="16" type="floor"/>
 <tile id="17" type="floor"/>
 <tile id="18" type="floor"/>
 <tile id="19" type="floor"/>
 <tile id="20" type="wall"/>
 <tile id="21" type="wall"/>
 <tile id="22" type="wall"/>
 <tile id="23" type="wall"/>
 <tile id="24" type="floor"/>
 <tile id="25" type="floor"/>
 <tile id="26" type="floor"/>
 <tile id="27" type="floor"/>
 <tile id="28" type="exit"/>
 <tile id="29" type="wall"/>
 <tile id="30" type="exit"/>
 <tile id="31" type="wall"/>
 <tile id="32" type="wall"/>
 <tile id="33" type="wall"/>
 <tile id="34" type="wall"/>
 <tile id="35" type="wall"/>
 <tile id="36" type="wall"/>
 <tile id="37" type="wall"/>
 <tile id="38" type="wall"/>
 <tile id="39" type="wall"/>
 <tile id="40" type="wall"/>
 <tile id="41" type="wall"/>
 <tile id="42" type="wall"/>
 <tile id="43" type="wall"/>
 <tile id="44" type="wall"/>
 <tile id="45" type="wall"/>
 <tile id="46" type="floor"/>
 <tile id="47" type="floor"/>
 <tile id="48" type="wall"/>
 <tile id="49" type="wall"/>
 <tile id="50" type="wall"/>
 <tile id="51" type="wall"/>
 <tile id="52" type="wall"/>
 <tile id="53" type="wall"/>
 <tile id="54" type="none"/>
 <tile id="55" type="wall"/>
 <tile id="56" type="wall"/>
 <tile id="57" type="wall"/>
 <tile id="58" type="wall"/>
 <tile id="59" type="wall"/>
 <tile id="60" type="wall"/>
 <tile id="61" type="wall"/>
 <tile id="62" type="wall"/>
 <tile id="63" type="wall"/>
 <tile id="64" type="wall"/>
 <tile id="65" type="wall"/>
 <tile id="66" type="wall"/>
 <tile id="67" type="wall"/>
 <tile id="68" type="wall"/>
 <tile id="69" type="wall"/>
 <tile id="70" type="floor"/>
 <tile id="71" type="floor"/>
 <tile id="72" type="wall"/>
 <tile id="73" type="wall"/>
 <tile id="74" type="wall"/>
 <tile id="75" type="wall"/>
 <tile id="76" type="wall"/>
 <tile id="77" type="wall"/>
 <tile id="78" type="none"/>
 <tile id="79" type="wall"/>
 <tile id="80" type="wall"/>
 <tile id="81" type="wall"/>
 <tile id="82" type="wall"/>
 <tile id="83" type="wall"/>
 <tile id="84" type="wall"/>
 <tile id="85" type="wall"/>
 <tile id="86" type="wall"/>
 <tile id="87" type="wall"/>
 <tile id="88" type="wall"/>
 <tile id="89" type="wall"/>
 <tile id="90" type="wall"/>
 <tile id="91" type="wall"/>
 <tile id="92" type="wall"/>
 <tile id="93" type="wall"/>
 <tile id="94" type="floor"/>
 <tile id="95" type="floor"/>
 <tile id="96" type="wall"/>
 <tile id="97" type="wall"/>
 <tile id="98" type="wall"/>
 <tile id="99" type="wall"/>
 <tile id="100" type="wall"/>
 <tile id="101" type="wall"/>
 <tile id="103" type="wall"/>
 <tile id="104" type="floor"/>
 <tile id="105" type="none"/>
 <tile id="106" type="none"/>
 <tile id="107" type="none"/>
 <tile id="108" type="none"/>
 <tile id="109" type="none"/>
 <tile id="110" type="none"/>
 <tile id="111" type="none"/>
</tileset>
