CC = gcc
FLAGS = -lSDL2 -lSDL2_image -lpthread
OUT = game.o
FILES = ../src/main.c ../src/game/game.c ../src/graphics/window.c ../src/util/util.c ../src/util/timer.c ../src/input/input.c ../src/graphics/sprite.c
all:
	$(CC) $(FILES) -o $(OUT) $(FLAGS)
