CC = g++
FILES = ../src/Main.cpp ../src/game/Gahoodmon.cpp ../src/game/Window.cpp ../src/util/Util.cpp ../src/util/Constants.cpp ../src/util/Timer.cpp ../src/util/FileUtil.cpp ../src/object/Sprite.cpp ../src/util/ImageUtil.cpp
FLAGS = -std=c++11
LIBS = -lSDL2 -lSDL2_image -lpthread
OUT = game.out
GAME:
	$(CC) $(FILES) -o $(OUT) $(FLAGS) $(LIBS)
